### ISSUE TITLE
Issue adding plugin

### ISSUE THREAD

**Issue by bijanmmarkes** [bambuser/cordova-plugin-bambuser#1]
This plugin cannot be added to my project, I get the following error:

Following error outputted everytime I try to add the cordova plugin via:
`Plugin:`cordova plugin add cordova-plugin-bambuser
----
`Error:`
```
plugins/cordova-plugin-bambuser/libbambuser-ios-0.9.21-190212/prebuilt/lib/libbambuser.a" not found!
```

I also tried removing and re-adding the ios platform.

Thanks!

**Comment by tomsun** [comment]
Can't reproduce locally, after installing with `cordova plugin add cordova-plugin-bambuser` i.e. current latest version from npm:
```
# ls -al plugins/cordova-plugin-bambuser/libbambuser-ios-0.9.21-190212/prebuilt/lib/libbambuser.a
-rw-r--r-- 1 root root 17311888 Apr  2 14:04 plugins/cordova-plugin-bambuser/libbambuser-ios-0.9.21-190212/prebuilt/lib/libbambuser.a

# cordova --version
8.1.2 (cordova-lib@8.1.1)
```

Sounds like you are up-to-date in terms of the plugin ( SDK 0.9.21 ) - which version of Cordova do you use?

In case you want to fix this manually, it is a matter of unzipping a file (two for cross-platform support), like so: https://github.com/bambuser/cordova-plugin-bambuser/blob/master/bin/install-sdk.js - which normally happens during `npm postinstall`

**Comment by tomsun** [comment]
A manual workflow could look something like this, first check out a local copy of cordova-plugin-bambuser separate from your project, outside of the plugins dir:

```
cd /some/local/path
git clone https://github.com/bambuser/cordova-plugin-bambuser.git
cd cordova-plugin-bambuser
npm install
```

expect the subdirectories `libbambuser-android-0.9.16-190212` and `libbambuser-ios-0.9.21-190212` to appear and check for any errors. please post the errors here if you try this out and find any. after install, you can rerun just the postinstall step with `npm run postinstall` in the cordova-plugin-bambuser directory if you like. alternatively, you can download the zip files and unzip them by hand into /some/local/path/cordova-plugin-bambuser

next, in your cordova project, use your local copy of the plugin as source. remove any pre-existing copies first.
```
cd /some/local/path/my-cordovaproject
cordova plugin remove cordova-plugin-bambuser
cordova plugin add /some/local/path/cordova-plugin-bambuser
```
