### ISSUE TITLE
【ios】App Store Connect Operation Warning

### ISSUE THREAD

**Issue by reon777** [bambuser/cordova-plugin-bambuser#11]
The following error occurred when uploading build file from Xcode to App Store Connect.

![image_2019_11_27T07_23_33_439Z](https://user-images.githubusercontent.com/29147283/69768376-b28b7400-11c3-11ea-9528-04d0451ba686.png)

```
App Store Connect Operation Warning
The app references non-public selectors in Payload/banbuser.app/banbuser: testStarted
```

Please let me know if you know the solution.

Thank you.

Environment
Xcode: 10.3
cordova-ios: 5.1.0
cordova-plugin-bambuser: 0.9.10

**Comment by tomsun** [comment]
@reon777 thanks for the report!

The Bambuser SDK contains a bandwidth tester that has an internal method named `testStarted`.
https://bambuser.com/docs/reference/ios-sdk-current/interface_bambuser_view.html#a290115cc5e66bd9825226af9d06b4c1a

AppStore Connect warns you that some private Apple framework also has a method with the same name that you are not supposed to call - which you are not calling in this case, but that part is harder for the analyzer to deduce https://stackoverflow.com/a/19379317 

It makes a bit of sense for Apple to emit warnings like that for verbose semi-unique method names like [_setAlwaysRunsAtForegroundPriority](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/209) but when they test for names like `testStarted` you're bound to see false positives like this.

Hopefully you can just ignore the warning and ship your app!

We will rename the method in a future SDK release if the problem persists.

**Comment by reon777** [comment]
Thank you for your quick answer.
I will ignore the warning
