### ISSUE TITLE
Implementation of broadcastIdReceived method

### ISSUE THREAD

**Issue by monsieurPaon** [bambuser/cordova-plugin-bambuser#13]
Hi @tomsun i try to implement the broadcastIdReceived. 

Actually the broadcastId arrived after my method send the we-have-id. 
I'm not familiar to swift and i need a little help on it.

this is my CordovaBambuserBroadcaster.m with the new method

the first nslog return Received broadcastIdReceived signal <CDVInvokedUrlCommand: 0x283900ba0> and after if i place broadcastId in the messageAsString the app crash because is not complete. If i let like following the messagestring with a status, the method retry and give me an id. But i can't transmit it to my javascript.

Our issue is broadcastId return first CDVInvokedUrlCommand and after the real broadcast id. We don't know how to deal with async result to transmit to javascript when is really present. 

- (void) broadcastIdReceived: (NSString *) broadcastId  {
    NSLog(@"Received broadcastIdReceived signal %@", broadcastId);
    CDVPluginResult *result = nil;
    if ((NSString *) broadcastId) {
        [self ensureLibbambuserIsBootstrapped];
        result = [CDVPluginResult resultWithStatus:(CDVCommandStatus)CDVCommandStatus_OK messageAsString:@"we-have-id"];
        [result setKeepCallbackAsBool:false];
        if (broadcastId != nil) {
        [self.commandDelegate sendPluginResult: result callbackId:onConnectionStatusChangeCallbackId ];
        }
    } else {
        result = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR];
    }
}

Please if someone can help me to end this .. @reon777 maybe ?

**Comment by monsieurPaon** [comment]
CordovaBambuserBroadcaster.h

#import <Cordova/CDVPlugin.h>
#import "libbambuser.h"

@interface CordovaBambuserBroadcaster : CDVPlugin {
BambuserView *bambuserView;
}

(void) setApplicationId: (CDVInvokedUrlCommand*) command;
(void) showViewfinderBehindWebView: (CDVInvokedUrlCommand*) command;
(void) hideViewfinder: (CDVInvokedUrlCommand*) command;
(void) setCustomData: (CDVInvokedUrlCommand*) command;
(void) setSendPosition: (CDVInvokedUrlCommand*) command;
(void) setTitle: (CDVInvokedUrlCommand*) command;
(void) startBroadcast: (CDVInvokedUrlCommand*) command;
(void) stopBroadcast: (CDVInvokedUrlCommand*) command;
(void) switchCamera: (CDVInvokedUrlCommand*) command;
(void) onConnectionError: (CDVInvokedUrlCommand*) command;
(void) onConnectionStatusChange: (CDVInvokedUrlCommand*) command;
(void) onOrientationChange: (CDVInvokedUrlCommand*) command;
// BambuserViewDelegate

(void) bambuserError: (enum BambuserError)errorCode message:(NSString*)errorMessage;
(void) broadcastStarted;
(void) broadcastIdReceived: (NSString*) broadcastId;
(void) broadcastStopped;
@EnD

**Comment by monsieurPaon** [comment]
broadcast.js

Broadcaster.broadcastIdReceived = function (successCallback, errorCallback) {
    var res;
    if (!successCallback) {
        console.log('broadcastIdReceived wait something');
        res = new Promise(function (resolve, reject) {
            successCallback = resolve;
            errorCallback = reject;
        });
        console.log('!successCallback', res);
    }
    if (errorCallback) {
        console.log('broadcastIdReceived wait error');
    }
    console.log(res);
    var startBroadcastResponseSent = false;
    var id = Broadcaster.addEventListener('connectionStatusChange', function (status) {
        console.log('in javascript', status);
        if (status === 'we-have-id') {
            Broadcaster.removeEventListener(id);
            if (!startBroadcastResponseSent) {
                startBroadcastResponseSent = true;
                successCallback(status);
            }
            return;
        }
    });
    console.log(id);
    execQueue(function () {
    }, function () {
        if (!startBroadcastResponseSent) {
            startBroadcastResponseSent = true;
            if (errorCallback) errorCallback.call(this, arguments);
        }
    }, 'CordovaBambuserBroadcaster', 'broadcastIdReceived', []);
    return res;
}

**Comment by tomsun** [comment]
@monsieurPaon thanks for the initial effort on this! Probably a good idea to add: some use-cases are impossible without it. I'll take a closer look in the coming week if time permits.

> We don't know how to deal with async result to transmit to javascript when is really present.
Think I would deal with it in a similar way to `onConnectionError`, `onConnectionStatusChange` etc

plugin side:
https://github.com/bambuser/cordova-plugin-bambuser/blob/master/www/broadcaster.js#L300

application side:
https://github.com/bambuser/bambuser-examplebroadcaster-ionic/blob/master/src/pages/broadcaster/broadcaster.ts#L112

**Comment by monsieurPaon** [comment]
Hi @tomsun really thank-your for your quick reply. I'm going to explore on this part ans see if i can implement something similar in the wait of your analysis.

**Comment by monsieurPaon** [comment]
hi @tomsun No success for the moment from my parts. I think i miss something .

**Comment by monsieurPaon** [comment]
hi @tomsun any news from your board ?

**Comment by tomsun** [comment]
@monsieurPaon the holidays got in the way, sorry. back on track now: draft of js listener + iOS side done, will do Android + some testing and then push a new release

**Comment by monsieurPaon** [comment]
@tomsun Really good news, can't wait to test it. Thank You !

**Comment by tomsun** [comment]
@monsieurPaon an implementation available in master now https://github.com/bambuser/cordova-plugin-bambuser/commit/8753f86012925fe63087e8b973ee5dc0b9a75710

Will push it to npm as 0.9.11 but that will have to wait until tomorrow at the earliest.

Also added usage basics to the example app https://github.com/bambuser/bambuser-examplebroadcaster-ionic/commit/206307d9927fae19a23aba42d5398f54d1ef1587
(you might also want to de(/re)-register your listener at strategic places if your app logic enters and leaves the broadcasting view)

Seems to work as expected on both iOS and Android. Let me know if you run into any issues.

![IMG_7399](https://user-images.githubusercontent.com/442510/72017879-4e060f00-326f-11ea-8e19-933ecd5968cf.PNG)

**Comment by tomsun** [comment]
0.9.11 is now available via npm as well

**Comment by monsieurPaon** [comment]
Nice @tomsun  work perfect ! Thank You so much.
