### ISSUE TITLE
Mutiple bambuser player on the same page

### ISSUE THREAD

**Issue by monsieurPaon** [bambuser/cordova-plugin-bambuser#14]
hi @tomsun we try to implement your native video player in component who are calling in a ion-slide. 

The first of the array work perfect, but if we go to the second slide, the player don't change and stay on the same videos. Could you confirm to me if it's possible to have multiples bambuserplayer load on the same page ?  

We have try the player-js solution but he don't load (sometimes yes, but it's rare).

By the way, have you ever test your streaming flow with another cordova plugin ?

**Comment by tomsun** [comment]
Hi @monsieurPaon !

I would recommend trying out the js player in that scenario: it should behave more or less like a `<video>` tag: if you want several videos side-by-side or animate them somehow, then normal css approaches should work fine.

In a Cordova context you may need to whitelist a couple of Bambuser domains or the web player won't be allowed to load its resources. This is what we do in the example app IIRC: https://github.com/bambuser/bambuser-exampleplayer-ionic/blob/master/config.xml#L9
Note also that AllowInlineMediaPlayback line, which might be needed to prevent iOS from going to fullscreen.

If you have other issues with the web player: are you able to share any additional details?

Bambuser's native player, when used by this plugin, is drawn behind the webview, detached from your DOM tree. To keep things simple this plugin doesn't implement an interface to draw anything other than a single fullscreen player right now. (The native side of the player does support multiple instances. In theory you could orchestrate them to show side by side, animate or whatever else on the native side, and put a Cordova bridge API on top of that. Not something I have immediate plans for personally)

**Comment by monsieurPaon** [comment]
Hi @tomsun :) 

So i have retry the player.js and now it's work. (before i have put my players in a ion-slider but this component look to crash sometimes. 

But i face the same issue actually 

this is html view where i list my players
`<ion-content class="ion-no-padding" *ngIf="bambuLives" id="scrollMain" [scrollEvents]="true"
             (ionScrollStart)="checkIfPlayerIsActif();" (ionScrollEnd)="logScrolling($event);">
    <ion-item lines="none" class="ion-no-padding scroll-test" *ngFor="let broadcast of bambuLives"
              (ionSlideTouchStart)="slideDidChange()" id="{{broadcast.id}}">
        <app-player-js (videoStatus)="getVideo($event)" *ngIf="broadcast.resourceUri" style="height: 100vh; width: 100vw;" (click)="checkIfPlayerIsActif()" [ressourceUri]="broadcast.resourceUri"></app-player-js>
    </ion-item>
</ion-content>`

this my player.js component 

`import {Component, ElementRef, EventEmitter, Input, NgZone, OnInit, Output, ViewChild} from '@angular/core';
import {NavController} from '@ionic/angular';

@Component({
    selector: 'app-player-js',
    templateUrl: './player-js.component.html',
    styleUrls: ['./player-js.component.scss'],
})
export class PlayerJsComponent implements OnInit {
    @Input() ressourceUri: string;
    @Output() videoStatus = new EventEmitter<string>();

    @ViewChild('player', {static: false}) playerEl: ElementRef;

    // Bind '<div #player>' in template to this.playerEl
    playerLog = [];
    showCloseButton = false;

    constructor(public element: ElementRef,
                public navCtrl: NavController,
                private zone: NgZone) {

        console.log('call player');
    }

    ngOnInit() {
        console.log(this.ressourceUri);
        this.ionViewDidEnter();
    }

    ionViewDidEnter() {
        console.log('starting javascript player');

        // BambuserPlayer is loaded to window in index.html
        const BambuserPlayer: any = window['BambuserPlayer'];

        // https://bambuser.com/docs/key-concepts/resource-uri/
        // The resourceUri is used to fetch the broadcast media
        //
        // Either use a broadcast provided by another page in the application
        let resourceUri = this.ressourceUri;
        console.log('inner is ' + this.ressourceUri);


        if (!resourceUri) {
            // ...or fall back to using a static resourceUri, for demo purposes
            resourceUri = 'https://cdn.bambuser.net/broadcasts/0b9860dd-359a-67c4-51d9-d87402770319?da_signature_method=HMAC-SHA256&da_id=9e1b1e83-657d-7c83-b8e7-0b782ac9543a&da_timestamp=1482921565&da_static=1&da_ttl=0&da_signature=cacf92c6737bb60beb1ee1320ad85c0ae48b91f9c1fbcb3032f54d5cfedc7afe';

            // normally you would get the resourceUri from the GET /broadcasts API
            // either by directly accessing it from your mobile app, or with your
            // custom backend as mediator.
            // https://bambuser.com/docs/api/get-broadcast-metadata/
        }

        window.addEventListener('message', function (event) {
            if (event.origin !== 'https://dist.bambuser.net') {
                // Don't trust messages from other origins
                return;
            }
            var videoEvent = event.data.videoEvent;
            if (videoEvent) {
                console.log('video event:', videoEvent.name);
            }

            if (videoEvent.name === 'ended') {
                console.log('cest fini bro');

            }
        }, false);

        this.returnVideoStatus('ended');

        // https://bambuser.com/docs/playback/web-player/#javascript-api
        var player = BambuserPlayer.create(document.getElementById('player'), resourceUri, {
            noFullscreen: true // Do not allow fullscreen
        });

        player.controls = false;

        const log = str => {
            // Ensure template is re-rendered even though caller might be an
            // event listener on an emitter outside of Angular's zone.
            // https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html
            this.zone.run(() => {
                this.playerLog.unshift(`${player.currentTime} ${player.duration} ${str}`);
            });
        };

        // Make player available in console, for debugging purposes
        console.log('The player object is now assigned to window.player. Try player.pause(), player.play(), player.currentTime etc...', player);
        window['player'] = player;

        // Log all player events as they occur, for debugging purposes
        [
            'canplay',
            'durationchange',
            'ended',
            'error',
            'loadedmetadata',
            'pause',
            'play',
            'playing',
            'progress',
            'seeked',
            'seeking',
            'timeupdate',
            'volumechange',
            'waiting'
        ].map(eventName => player.addEventListener(eventName, e => log(eventName)));

        player.play();
        this.showCloseButton = true;
    }

    closePlayer() {
        // Relevant only if player is opened as a modal
        this.navCtrl.pop();
    }

    returnVideoStatus(geo) {
        this.videoStatus.emit(geo);
    }

    ionViewWillLeave() {
        // Remove player from DOM.
        //
        // By design, Ionic tabs controller keeps the page alive in the background
        // when navigating away. Leaving a player in the background might be
        // resource-consuming and otherwise unexpected though...
        //
        // If retaining the player state is desired when navigating back and forth,
        // consider replacing the below assignment with player.pause() / player.play()

        console.log('closing javascript player');
        this.playerEl.nativeElement.innerHTML = '';
        this.playerLog = [];
    }

    tuchIt() {
        console.log('closing javascript player');
        this.playerEl.nativeElement.innerHTML = '';
        this.playerLog = [];
    }

}
`

and this is the .ts from the view where i list all players

`import {Component, NgZone, OnInit, ViewChild} from '@angular/core';
import {UserService} from '../services/user.service';
import {TagService} from '../services/tag.service';
import {PublicationService} from '../services/publication.service';
import {Platform} from '@ionic/angular';
import {LivestreamService} from '../services/livestream.service';
import {StreamingMedia, StreamingVideoOptions} from '@ionic-native/streaming-media/ngx';
import {DomSanitizer} from '@angular/platform-browser';
import {IonContent} from '@ionic/angular';
import {IonSlides} from '@ionic/angular';
import * as moment from 'moment';

const APPLICATION_ID = '';

@Component({
    selector: 'app-flow',
    templateUrl: './flow.page.html',
    styleUrls: ['./flow.page.scss'],
})
export class FlowPage implements OnInit {
    @ViewChild('ion-content', {static: true}) content: IonContent;
    @ViewChild('mySliderWelcome', {static: true}) slides: IonSlides;

    slideOpts = {
        // direction: 'vertical',
        initialSlide: 1,
        speed: 400,
        loop: true
    };

    videoStatus: any;
    geo: any;

    loadSlider = false;

    isItemAvailable = false;
    items: any;
    users: any;
    tags: any;
    user: any;
    tag: any;
    publications: any;
    lives: any;
    bambuLives: any;
    bambuUserLive: any;
    dangerousVideoUrl: any;
    videoUrl: any;
    ressourceUri: any;

    player: any;
    playerLog = [];
    showCloseButton = false;

    // Declare the variable (in this case isItemAvailable) and initialize the items with false

    constructor(public userService: UserService, public tagService: TagService,
                public publicationService: PublicationService,
                public platform: Platform, private zone: NgZone,
                public liveStreamService: LivestreamService,
                private streamingMedia: StreamingMedia, private sanitizer: DomSanitizer) {
    }


    async ionViewDidEnter() {
        this.getAllLives();
        this.loadSlider = false;
    }

    logScrolling(e) {
        console.log(e);
    }

    checkIfPlayerIsActif() {
        // const theContent = document.getElementById('scrollMain');
        //
        // if (this.loadSlider) {
        //     this.closePlayer();
        // }

        // this.closePlayer();

        console.log('scroll start');

        // theContent.scrollByPoint(0, 10);
    }

    ngOnInit() {

    }

    slideDidChange(value) {
        console.log('slide has change ' + value);
        // Using array syntax workaround, since types are not declared.
        this.loadSlider = true;

        if (window['bambuser'] && window['bambuser']['player']) {
            this.player = window['bambuser']['player'];
            this.player.setApplicationId('yusDOP4obNJqUNKF4x0WOA');
        } else {
            console.log('Cordova plugin not installed or running in a web browser');
        }
        // this.createPlayer(value);
    }

    getAllLives() {
        this.publicationService.getAllPublicationsCoolSpot('3').subscribe(result => {
            this.lives = result;
            console.log(result);

            let publiLives = [];

            for (var i = 0; i < this.lives.length; i++) {
                let pub = this.lives[i];

                this.liveStreamService.getOneKikStream(pub.liveStreams[0]).subscribe(live => {
                    this.bambuUserLive = live;
                    console.log(this.bambuUserLive.bambuserId);

                    this.liveStreamService.getOneLivestream(this.bambuUserLive.bambuserId).subscribe(bamb => {
                        publiLives.push(bamb);
                    });
                });
            }

            console.log(publiLives);
            this.bambuLives = publiLives;

        });
    }


    getVideo(geo) {
        this.videoStatus = geo;
        console.log(this.videoStatus);
    }

    // include js player directly in flow
    // scroll() {
    //     const theContent = document.getElementById('scrollMain');
    //
    //     console.log('scroll ');
    //     theContent.scrollToPoint(0, 1, 500);
    //     // theContent.getScrollElement();
    //     console.log(this.content);
    //     window.scrollTo(0, 500);
    //
    //     // this.content.scrollToPoint(0, 1);
    // }
    // createPlayer(ressourceUrii) {
    //     console.log('starting javascript player');
    //
    //     // BambuserPlayer is loaded to window in index.html
    //     const BambuserPlayer: any = window['BambuserPlayer'];
    //
    //     // https://bambuser.com/docs/key-concepts/resource-uri/
    //     // The resourceUri is used to fetch the broadcast media
    //     //
    //     // Either use a broadcast provided by another page in the application
    //     let resourceUri = ressourceUrii;
    //     console.log('inner is ' + this.ressourceUri);
    //
    //
    //     if (!resourceUri) {
    //         // ...or fall back to using a static resourceUri, for demo purposes
    //         resourceUri = 'https://cdn.bambuser.net/broadcasts/0b9860dd-359a-67c4-51d9-d87402770319?da_signature_method=HMAC-SHA256&da_id=9e1b1e83-657d-7c83-b8e7-0b782ac9543a&da_timestamp=1482921565&da_static=1&da_ttl=0&da_signature=cacf92c6737bb60beb1ee1320ad85c0ae48b91f9c1fbcb3032f54d5cfedc7afe';
    //
    //         // normally you would get the resourceUri from the GET /broadcasts API
    //         // either by directly accessing it from your mobile app, or with your
    //         // custom backend as mediator.
    //         // https://bambuser.com/docs/api/get-broadcast-metadata/
    //     }
    //
    //     window.addEventListener('message', function (event) {
    //         if (event.origin !== 'https://dist.bambuser.net') {
    //             // Don't trust messages from other origins
    //             return;
    //         }
    //         var videoEvent = event.data.videoEvent;
    //         if (videoEvent) {
    //             console.log('video event:', videoEvent.name);
    //         }
    //
    //         if (videoEvent.name === 'ended') {
    //             console.log('cest fini bro');
    //         }
    //     }, false);
    //
    //     // https://bambuser.com/docs/playback/web-player/#javascript-api
    //     var player = BambuserPlayer.create(document.getElementById('player'), resourceUri, {
    //         noFullscreen: true // Do not allow fullscreen
    //     });
    //
    //     player.controls = false;
    //
    //     const log = str => {
    //         // Ensure template is re-rendered even though caller might be an
    //         // event listener on an emitter outside of Angular's zone.
    //         // https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html
    //         this.zone.run(() => {
    //             this.playerLog.unshift(`${player.currentTime} ${player.duration} ${str}`);
    //         });
    //     };
    //
    //     // Make player available in console, for debugging purposes
    //     console.log('The player object is now assigned. Try player.pause(), player.play(), player.currentTime', player);
    //     window['player'] = player;
    //
    //     // Log all player events as they occur, for debugging purposes
    //     [
    //         'canplay',
    //         'durationchange',
    //         'ended',
    //         'error',
    //         'loadedmetadata',
    //         'pause',
    //         'play',
    //         'playing',
    //         'progress',
    //         'seeked',
    //         'seeking',
    //         'timeupdate',
    //         'volumechange',
    //         'waiting'
    //     ].map(eventName => player.addEventListener(eventName, e => log(eventName)));
    //
    //
    //     player.play();
    //     this.showCloseButton = true;
    // }


    // for native player only
    // closePlayer() {
    //     // Relevant only if player is opened as a modal
    //     this.loadSlider = false;
    //     document.getElementsByTagName('body')[0].classList.remove('show-native-player');
    //
    //     // this.player.hidePlayer();
    //     // this.player.close();
    // }

    // async createPlayer(valueresourceUri) {
    //     // Engage our Ionic CSS background overrides that ensure native player behind webview is visible.
    //     document.getElementsByTagName('body')[0].classList.add('show-native-player');
    //
    //     console.log(this.player);
    //     console.log(valueresourceUri);
    //     console.log('starting native player');
    //
    //     if (!this.player) {
    //         await new Promise(resolve => setTimeout(resolve, 1000)).then(() => {
    //             console.log('not ready');
    //         });
    //
    //         // return;
    //     }
    //
    //     console.log('Displaying player behind webview');
    //
    //
    //     if (this.player) {
    //         this.player.showPlayerBehindWebView();
    //     }
    //
    //     let resourceUri = valueresourceUri;
    //
    //     if (!resourceUri) {
    //         resourceUri = 'https://cdn.bambuser.net/groups/77038/broadcasts?by_authors=&title_contains=&has_any_tags=&has_all_tags=&order=live&da_id=b86dfb86-dd8a-70e4-6929-34931454cfa7&da_timestamp=1555368368&da_signature_method=HMAC-SHA256&da_ttl=0&da_static=1&da_signature=ce6e40acbc18585ea8b677efc91a7acf715e7cb6401104ed42f73e5b0277f5c9';
    //     }
    //
    //     const log = str => {
    //         this.zone.run(() => {
    //             this.playerLog.unshift(`${moment().format('hh:mm:ss')} ${str}`);
    //         });
    //     };
    //
    //     [
    //         'broadcastLoaded',
    //         'stateChange',
    //     ].map(eventName => this.player.addEventListener(eventName, e => log(eventName + ': ' + JSON.stringify(e))));
    //
    //     this.player.loadBroadcast(resourceUri);
    // }

    // next(slides) {
    //     slides.slideNext();
    //     this.loadSlider = false;
    //
    //     document.getElementsByTagName('body')[0].classList.remove('show-native-player');
    // }
    //
    // nxt(slides) {
    //     document.getElementById('player').addEventListener('click', function () {
    //         slides.slideNext();
    //     });
    // }

    // getUsers() {
    //     this.userService.getAllUsers().subscribe(users => {
    //         console.log(users);
    //         this.users = users;
    //         this.items = [];
    //
    //         // for (var i = 0; i < users.length; i++) {
    //         //     let user = users[i];
    //         //
    //         //     this.items.push(['@' + user.username, user.id]);
    //         //
    //         //     // Do what you want from here
    //         // }
    //
    //         for (const user of this.users) {
    //             this.items.push(['@' + user.username, user.id]);
    //         }
    //
    //         console.log(this.items);
    //
    //     });
    // }
    //
    // getAllTags() {
    //     this.tagService.getAllTag().subscribe(tags => {
    //         console.log(tags);
    //         this.tags = tags;
    //
    //         for (const tag of this.tags) {
    //             this.items.push(['#' + tag.name, tag.id]);
    //         }
    //
    //         console.log(this.items);
    //
    //     });
    // }
    //
    // initializeItems() {
    //     this.getUsers();
    //     this.getAllTags();
    // }
    //
    // getItems(ev: any) {
    //     // Reset items back to all of the items
    //     this.initializeItems();
    //
    //     // set val to the value of the searchbar
    //     const val = ev.target.value;
    //
    //     // if the value is an empty string don't filter the items
    //     if (val && val.trim() !== '') {
    //         this.isItemAvailable = true;
    //         this.items = this.items.filter((item) => {
    //             return (item.toLowerCase().indexOf(val.toLowerCase()) > -1);
    //         });
    //     }
    // }
}
`

**Comment by monsieurPaon** [comment]
The issue is the first player load and play good, but all players after are empty (but i see all videos are playing) We looking to do a fullscreen player who is starting when we are on the view.

<img width="356" alt="Capture d’écran 2020-01-20 à 19 39 26" src="https://user-images.githubusercontent.com/46219142/72766067-90a7df80-3bbd-11ea-9c9d-9d652c5270fc.png">
<img width="351" alt="Capture d’écran 2020-01-20 à 19 39 39" src="https://user-images.githubusercontent.com/46219142/72766070-96052a00-3bbd-11ea-9262-08f021c0e8f5.png">

**Comment by monsieurPaon** [comment]
Sorry for the presentation

**Comment by tomsun** [comment]
Hi, looks like you've kept that idea of single global player div from the example
```
// Bind '<div #player>' in template to this.playerEl
@ViewChild('player', {static: false}) playerEl: ElementRef;
```

If you want multiple concurrent player instance it would probably be best to give them a container each, somehow.

(Or, for a slider, at least two: one for the leaving player and another for the entering player, since both are on screen at the same time during the animation (probably), and then reuse those two cleverly... assuming it is ok to throw away the ones not currently displaying)

**Comment by monsieurPaon** [comment]
Hi @tomsun , when you say **If you want multiple concurrent player instance it would probably be best to give them a container each, somehow.**

If a i use a custom id on each component it will be good you think ?

**Comment by tomsun** [comment]
@monsieurPaon yep, at least if you use that same method to query them

```html
...
<div #player1></div>
...
<div #player2></div>
...
```

```ts
// Bind to '<div #player1>'
@ViewChild('player1', {static: false}) player1El: ElementRef;

// Bind to  '<div #player2>'
@ViewChild('player2', {static: false}) player2El: ElementRef;

...
```

**Comment by monsieurPaon** [comment]
Hi @tomsun 

Hi try to add a input to my component where i pass a custom id **playerIds**

`<ion-content class="ion-no-padding" *ngIf="bambuLives" id="scrollMain">
    <ion-item lines="none" class="ion-no-padding scroll-test" *ngFor="let broadcast of bambuLives"
              (ionSlideTouchStart)="slideDidChange()" id="{{broadcast.id}}">
        <app-player-js *ngIf="broadcast.resourceUri && broadcast.string" (videoStatus)="getVideo($event)"
                       style="height: 100vh; width: 100vw;" (click)="checkIfPlayerIsActif()"
                       [ressourceUri]="broadcast.resourceUri" [playerIds]="broadcast.string"></app-player-js>
    </ion-item>
</ion-content>`

Now each player have a custom id, but i'm always zacing the same issue. I never have two player load.. In my chrome navigator i see error like 429 or ressourceUri is missing (but his clearly present)

I really need to delivered this work... 

this my player-js component 

`import {Component, ElementRef, EventEmitter, Input, NgZone, OnInit, Output, ViewChild} from '@angular/core';
import {NavController} from '@ionic/angular';

@Component({
    selector: 'app-player-js',
    templateUrl: './player-js.component.html',
    styleUrls: ['./player-js.component.scss'],
})
export class PlayerJsComponent implements OnInit {
    @Input() ressourceUri: string;
    @Input() playerIds: string;
    @Output() videoStatus = new EventEmitter<string>();

    @ViewChild('player', {static: false}) playerEl: ElementRef;

    // Bind '<div #player>' in template to this.playerEl
    playerLog = [];
    showCloseButton = false;
    playerId: any;

    constructor(public element: ElementRef,
                public navCtrl: NavController,
                private zone: NgZone) {

        console.log('call player');
    }

    ngOnInit() {
        console.log(this.ressourceUri);

        if (this.playerIds) {
            this.ionViewDidEnter();
        }
    }

    ionViewDidEnter() {
        console.log(this.playerIds);
        console.log('starting javascript player');

        // BambuserPlayer is loaded to window in index.html
        const BambuserPlayer: any = window['BambuserPlayer'];

        // https://bambuser.com/docs/key-concepts/resource-uri/
        // The resourceUri is used to fetch the broadcast media
        //
        // Either use a broadcast provided by another page in the application
        let resourceUri = this.ressourceUri;
        let playerTag = this.playerIds;
        console.log('inner is ' + this.ressourceUri);


        if (!resourceUri) {
            // ...or fall back to using a static resourceUri, for demo purposes
            resourceUri = 'https://cdn.bambuser.net/broadcasts/0b9860dd-359a-67c4-51d9-d87402770319?da_signature_method=HMAC-SHA256&da_id=9e1b1e83-657d-7c83-b8e7-0b782ac9543a&da_timestamp=1482921565&da_static=1&da_ttl=0&da_signature=cacf92c6737bb60beb1ee1320ad85c0ae48b91f9c1fbcb3032f54d5cfedc7afe';

            // normally you would get the resourceUri from the GET /broadcasts API
            // either by directly accessing it from your mobile app, or with your
            // custom backend as mediator.
            // https://bambuser.com/docs/api/get-broadcast-metadata/
        }

        window.addEventListener('message', function (event) {
            if (event.origin !== 'https://dist.bambuser.net') {
                // Don't trust messages from other origins
                return;
            }
            var videoEvent = event.data.videoEvent;
            if (videoEvent) {
                console.log('video event:', videoEvent.name);
            }

            if (videoEvent.name === 'ended') {
                console.log('cest fini bro');

            }
        }, false);


        this.returnVideoStatus('ended');
        // var player = BambuserPlayer.create(this.playerEl.nativeElement, resourceUri);

        if (this.playerIds && resourceUri) {
            // https://bambuser.com/docs/playback/web-player/#javascript-api
            var player = BambuserPlayer.create(document.getElementById(playerTag), resourceUri, {
                noFullscreen: true // Do not allow fullscreen
            });
        }

        player.controls = false;

        const log = str => {
            // Ensure template is re-rendered even though caller might be an
            // event listener on an emitter outside of Angular's zone.
            // https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html
            this.zone.run(() => {
                this.playerLog.unshift(`${player.currentTime} ${player.duration} ${str}`);
            });
        };

        // Make player available in console, for debugging purposes
        console.log('The player object is now assigned to window.player. Try player.pause(), player.play(), player.currentTime etc...', player);
        window['player'] = player;

        // Log all player events as they occur, for debugging purposes
        [
            'canplay',
            'durationchange',
            'ended',
            'error',
            'loadedmetadata',
            'pause',
            'play',
            'playing',
            'progress',
            'seeked',
            'seeking',
            'timeupdate',
            'volumechange',
            'waiting'
        ].map(eventName => player.addEventListener(eventName, e => log(eventName)));

        player.play();
        this.showCloseButton = true;
    }

    closePlayer() {
        // Relevant only if player is opened as a modal
        this.navCtrl.pop();
    }

    returnVideoStatus(geo) {
        this.videoStatus.emit(geo);
    }

    ionViewWillLeave() {
        // Remove player from DOM.
        //
        // By design, Ionic tabs controller keeps the page alive in the background
        // when navigating away. Leaving a player in the background might be
        // resource-consuming and otherwise unexpected though...
        //
        // If retaining the player state is desired when navigating back and forth,
        // consider replacing the below assignment with player.pause() / player.play()

        console.log('closing javascript player');
        this.playerEl.nativeElement.innerHTML = '';
        this.playerLog = [];
    }

    tuchIt() {
        console.log('closing javascript player');
        // this.playerEl.nativeElement.innerHTML = '';
        var player = [];
        this.playerLog = [];
    }

}
`

and the player-js html 

`<div class="player-container" (click)="tuchIt()">
  <div *ngIf="playerIds" style="height: 100%;" id="{{playerIds}}"></div>
</div>`

**Comment by tomsun** [comment]
Oh, you built a component around the player and repeating it,  that’s probably smart! In that case my id comment doesn’t apply. Do you still have a `<div #player></div>` in your player-js.component.html ?

**Comment by monsieurPaon** [comment]
Yes @tomsun exactly. 

This is my player-js.component.html  

<div class="player-container" (click)="tuchIt()">
  <div *ngIf="playerIds" style="height: 100%;" id="{{playerIds}}"></div>
</div>

**Comment by monsieurPaon** [comment]
Hi @tomsun i have now multiple player, this is nice. But my last issue is about control. I have put a function to play or stop the video (very basic from your documentation)
`       playPause() {
        return player.paused ? player.play() : player.pause();
    }
`

`<div class="player-container">
  <div #player style="height: 100%;" id="{{playerIds}}" (click)="playPause()"></div>
</div>`

But the function work only on the last player of my array of player. I think is related to the video player because is map only with the #player . Any idea for individual control ?

**Comment by tomsun** [comment]
Hi, Do you still have each player contained in a component (you called it `<app-player-js>` above) ? If so, I would expect that your `play()` function, if implemented inside app-player-js, would map correctly to each underlying Bambuser player.

—-

Do you have an array app-player-js instances or an array of:
`BambuserPlayer.create(this.playerEl.nativeElement, resourceUri);`? Is this list defined in a parent component?

—-

(In react you have to provide id:s when working with lists to avoid getting the items mixed up in weird ways when reused during re-render. not aware any similar quirks with ngif in angular though... https://angular.io/api/common/NgIf
)

—-

Here are the docs on template reference variables and ViewChild, in case they provide some clues
https://angular.io/guide/template-syntax#ref-vars
https://angular.io/api/core/ViewChild#description

**Comment by monsieurPaon** [comment]
all my components <app-player-js> are in a ngfor in a flow.coponent . Each app player have the same codes. I notice each video player in iframe have the same ID, but i notice in the iframe an individual ID. How can i map each player to insure play pause function ? 

> 
 <ion-item lines="none" class="ion-no-padding scroll-test" *ngFor="let broadcast of bambuLives"
  id="{{broadcast.id}}">
        <app-player-js *ngIf="broadcast.resourceUri" (videoStatus)="getVideo($event)"
                       style="height: 100vh; width: 100vw;"
                       [ressourceUri]="broadcast.resourceUri" [playerIds]="broadcast.string">
        </app-player-js>
    </ion-item>
> 
this is my player-js.ts

export class PlayerJsComponent implements OnInit {
    @Input() ressourceUri: string;
    @Input() playerIds: string;
    @Output() videoStatus = new EventEmitter<string>();

    @ViewChild('player', {static: true}) playerEl: ElementRef;
    // @ViewChild('player') playerEl: ElementRef;


    // Bind '<div #player>' in template to this.playerEl
    playerLog = [];
    showCloseButton = false;
    playerId: any;

    constructor(public element: ElementRef,
                public navCtrl: NavController,
                private zone: NgZone) {

        // this.playerEl.nativeElement.innerHTML = this.playerIds;
    }

    ngOnInit() {
        console.log(this.ressourceUri);

        if (this.playerIds) {
            this.ionViewDidEnter();
        }

    }

    ionViewDidEnter() {
        // console.log(this.playerIds);
        // console.log('starting javascript player');

        console.log(this.playerEl.nativeElement.innerHTML);
        const BambuserPlayer: any = window['BambuserPlayer'];

        let resourceUri = this.ressourceUri;
        let playerTag = this.playerIds;

        if (!resourceUri) {
            // ...or fall back to using a static resourceUri, for demo purposes
            resourceUri = 'https://cdn.bambuser.net/broadcasts/0b9860dd-359a-67c4-51d9-d87402770319?da_signature_method=HMAC-SHA256&da_id=9e1b1e83-657d-7c83-b8e7-0b782ac9543a&da_timestamp=1482921565&da_static=1&da_ttl=0&da_signature=cacf92c6737bb60beb1ee1320ad85c0ae48b91f9c1fbcb3032f54d5cfedc7afe';
        }

        window.addEventListener('message', function (event) {
            if (event.origin !== 'https://dist.bambuser.net') {
                // Don't trust messages from other origins
                return;
            }
            var videoEvent = event.data.videoEvent;

            if (videoEvent) {
                // console.log('video event:', videoEvent.name);
            }

            if (videoEvent.name === 'ended') {
                console.log('Video fini');
                // player.play();

            }
        }, false);

        this.returnVideoStatus('ended');
        var player = BambuserPlayer.create(this.playerEl.nativeElement, resourceUri, {
            noFullscreen: true // Do not allow fullscreen
        });

        player.controls = false;

        const log = str => {
            this.zone.run(() => {
                this.playerLog.unshift(`${player.currentTime} ${player.duration} ${str}`);
            });
        };

        // Player object assigned to window.player. Try player.pause(), player.play(), player.currentTime etc...
        console.log(player);
        window[this.playerIds] = player;

        // // Log all player events as they occur, for debugging purposes
        // [
        //     'canplay',
        //     'durationchange',
        //     'ended',
        //     'error',
        //     'loadedmetadata',
        //     'pause',
        //     'play',
        //     'playing',
        //     'progress',
        //     'seeked',
        //     'seeking',
        //     'timeupdate',
        //     'waiting'
        // ].map(eventName => player.addEventListener(eventName, e => log(eventName)));

        // player.play();
        this.showCloseButton = true;

        const playerLol = this.playerIds;

        document.getElementById(this.playerIds).addEventListener('click', function() {

            console.log('click' + player);
            // return player.paused ? player.play() : player.pause();
        });

    }


    closePlayer() {
        // Relevant only if player is opened as a modal
        this.navCtrl.pop();
    }

    returnVideoStatus(geo) {
        this.videoStatus.emit(geo);
    }

    ionViewWillLeave() {

        console.log('closing javascript player');
        this.playerEl.nativeElement.innerHTML = '';
        this.playerLog = [];
    }

    // tuchIt() {
    //     return this.player.paused ? player.play() : player.pause();
    // }

    // return player.paused ? player.play() : player.pause();
    //
    // console.log('Pause the video');
    // player.pause();


}


If you want i can share you the repo or the copy of my code. Thanks @tomsun .

**Comment by monsieurPaon** [comment]
Hi @tomsun do you think it's possible to use another player, or is only restrict to the bambuser player ?

**Comment by monsieurPaon** [comment]
Just to follow up we have find a solution.

**Comment by tomsun** [comment]
@monsieurPaon ok, awesome! I didn't have time to attempt to reproduce in an angular setting yet but it should indeed work fine if rigged correctly. Let us know if anything else comes up
