### ISSUE TITLE
[Android] Issue using plugin with another plugin that uses camera 

### ISSUE THREAD

**Issue by weiz18** [bambuser/cordova-plugin-bambuser#6]
Hey,

We are having issue using this plugin alongside another plugin which requires the native camera feature as well.  When trying to build, we are getting a `android manifest merger failed` error which is caused by the duplicated entry.  
 
Bambuser ->
`<uses-feature android:name="android.hardware.camera" android:required="false" />`

Camera (https://github.com/apache/cordova-plugin-camera)-> it also uses the camera but that have required option set to true.
`<uses-feature android:name="android.hardware.camera" android:required="true" />`

This is failing our CI build because everything is done automatically  and we can't remove the duplicated entry manually.  Do you know if there is a way to resolve this conflict or you can update the required to be `true`, so it can be merged automatically. 

Thanks

**Comment by weiz18** [comment]
Similar issue, https://github.com/bitpay/cordova-plugin-qrscanner/issues/111. I think we can safely remove required filed to avoid with other field .

**Comment by tomsun** [comment]
Hi @weiz18, thanks for the report!

I tried reproducing in CI

`cordova-paramedic --platform android --plugin $PWD --plugin cordova-plugin-camera`
does not fail though.

and `cordova-paramedic --platform android --plugin cordova-plugin-qrscanner`
fails on its own without involving our plugin.

Any quick tips on how to create a failing test?

**Comment by tomsun** [comment]
`cordova-plugin-camera` does not seem to declare any `<uses-feature>` tags, whereas
`cordova-plugin-qrscanner` provide a couple.

> In general, you should always make sure to declare <uses-feature> elements for all of the features that your application requires

> When you declare android:required="false" for a feature, it means that the application prefers to use the feature if present on the device, but that it is designed to function without the specified feature, if necessary.
https://developer.android.com/guide/topics/manifest/uses-feature-element?authuser=1

Currently, cordova-plugin-bambuser uses this pattern from our native example app:
```
<uses-feature android:name="android.hardware.camera.any" android:required="true" />
<uses-feature android:name="android.hardware.camera" android:required="false" />
```
( https://dist.bambuser.com/android_sdk/libbambuser-android-0.9.17-190319.zip )
...which translates roughly to "In the Google Play listing, show this app even
if the device lacks a proper back camera, but hide me from devices that have no cameras".
By using that configuration, your app is available to all devices where broadcasting is possible, 

On the other hand, perhaps a plugin shouldn't be too eager to insist how the resulting app
is filtered in Google Play. Maybe cordova-plugin-camera's choice of letting the developer
choose or letting Google Play infer this information, is a better path re compatibility etc.

Pro: avoid clashing with other plugins 
Con: you might have to do some additional work yourself if you care about those odd single-camera devices.

Leaning towards doing a release without those `uses-feature`-tags and see if that generates any reactions and feedback

**Comment by tomsun** [comment]
@weiz18 adjusted in 0.9.10
